In [1]:
#NUMPY PARA ANALISIS DE DATOS
import numpy as np

lista=[1,2,3,4]

array=np.array (lista)

array


array([1, 2, 3, 4])

In [2]:
lista2=[[1,2,3],[4,5,6],[7,8,9]]

lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
array2=np.array(lista2)

array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
array3=np.arange(5)

array3

array([0, 1, 2, 3, 4])

In [10]:
array4 = np.arange(2,10)
array4

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array5=np.arange(2,20,2)
array5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(5,8,50)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [18]:
np.eye(20)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [20]:
#Aleatorios
np.random.rand(5,3)

array([[0.34538415, 0.61066367, 0.60470557],
       [0.95169361, 0.55410806, 0.09345708],
       [0.60401669, 0.05043165, 0.27596252],
       [0.91677314, 0.16169993, 0.98458829],
       [0.72280843, 0.47174427, 0.96480471]])

In [21]:
np.random.randn(5,3)

array([[-1.23000457, -0.05037438, -0.02726526],
       [-0.52001023,  1.26146144, -0.48432833],
       [-0.25004796,  0.92495257, -0.0034246 ],
       [ 0.39706038,  0.6190123 ,  0.71168143],
       [ 1.20908313,  2.15204918, -0.2929515 ]])

In [25]:
np.random.randint(1,20)


2

In [26]:
np.random.randint(1,5,8)

array([1, 1, 3, 2, 2, 1, 2, 4])

In [28]:
#reshape
array=np.random.randint(1,100,20)
array

array([40, 76, 54, 27, 69,  8, 25, 12, 32, 58, 20, 62,  5,  1, 47, 46,  2,
       31, 39, 11])

In [31]:
matriz=array.reshape(4,5)
matriz

array([[40, 76, 54, 27, 69],
       [ 8, 25, 12, 32, 58],
       [20, 62,  5,  1, 47],
       [46,  2, 31, 39, 11]])

In [32]:
array = np.random.randint(1,100,30)
array

array([97, 99, 47, 90, 81, 78, 32,  2, 29, 12, 82, 74, 96,  1, 24, 36, 92,
       38, 12, 60, 96, 33, 13, 99, 82, 34, 83, 98, 69, 76])

In [36]:
valor_max = array.max()
posicion_max=array.argmax()
valor_max
posicion_max

1

In [37]:
valor_min = array.min()
posicion_min=array.argmin()
valor_min
posicion_min

13

In [43]:
#indexacion

array = np.random.randint(1,100,30)
array

array([59, 37, 41, 40, 58, 46, 23, 98, 60, 17, 12, 19, 38, 78, 26,  6,  4,
       75, 98,  6, 67,  9, 93, 48, 76, 77, 79, 83, 30, 70])

In [44]:
array[8]

60

In [45]:
array[10:20]

array([12, 19, 38, 78, 26,  6,  4, 75, 98,  6])

In [46]:
array[:]

array([59, 37, 41, 40, 58, 46, 23, 98, 60, 17, 12, 19, 38, 78, 26,  6,  4,
       75, 98,  6, 67,  9, 93, 48, 76, 77, 79, 83, 30, 70])

In [47]:
array[5:]

array([46, 23, 98, 60, 17, 12, 19, 38, 78, 26,  6,  4, 75, 98,  6, 67,  9,
       93, 48, 76, 77, 79, 83, 30, 70])

In [48]:
array[:10]

array([59, 37, 41, 40, 58, 46, 23, 98, 60, 17])

In [49]:
array2=array.copy()
array2

array([59, 37, 41, 40, 58, 46, 23, 98, 60, 17, 12, 19, 38, 78, 26,  6,  4,
       75, 98,  6, 67,  9, 93, 48, 76, 77, 79, 83, 30, 70])

In [50]:
#arreglos de varias dimensiones

array=np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
diagonal=np.diag(array)
diagonal

array([1, 5, 9])

In [57]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [56]:
array[:,0]

array([1, 4, 7])

In [60]:
#condicional

array=np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
condicion = array>5
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [65]:
array[condicion]

array([6, 7, 8, 9])

In [67]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

In [70]:
#operaciones con array
array=np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
array+array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
array*array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [73]:
array-array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
array*100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [75]:
array-1


array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [76]:
array2=np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
array2-array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [78]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [79]:
np.max(array)

9

In [80]:
np.min(array)

0